angular.module("PipelineDesigner",
    [
        "PipelineDesigner.filters",
        "ngResource",
        "EavConfiguration",
        "EavServices",
        "eavTemplates",
        "eavNgSvcs",
        "EavAdminUi",
        "eavEditEntity"
    ]);
